// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Soltec.axControl.Server.Data;

#nullable disable

namespace Soltec.axControl.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CerealFila", b =>
                {
                    b.Property<int>("CerealesId")
                        .HasColumnType("int");

                    b.Property<int>("FilasId")
                        .HasColumnType("int");

                    b.HasKey("CerealesId", "FilasId");

                    b.HasIndex("FilasId");

                    b.ToTable("FilaCereales", (string)null);
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.Cereal", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Cereales");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.Chofer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SujetoId")
                        .HasColumnType("int");

                    b.Property<int>("TransportistaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SujetoId");

                    b.HasIndex("TransportistaId");

                    b.ToTable("Choferes");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.Circuito", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Circuitos");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.ComprobanteHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdenTransitoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrdenTransitoId");

                    b.ToTable("HistorialesComprobante");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.Estado", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.EstadoHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdenTransitoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("OrdenTransitoId");

                    b.ToTable("HistorialesEstado");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.Fila", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("TipoOperacion")
                        .HasColumnType("int");

                    b.Property<int>("ZonaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZonaId");

                    b.ToTable("Filas");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.FilaHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("FilaId")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdenTransitoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FilaId");

                    b.HasIndex("OrdenTransitoId");

                    b.ToTable("HistorialesFila");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.OrdenTransito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CerealId")
                        .HasColumnType("int");

                    b.Property<int>("ChoferId")
                        .HasColumnType("int");

                    b.Property<int>("CircuitoId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("FilaId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroComprobante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatenteAcoplado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatenteChasis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatenteOpc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<string>("TagRFID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransporteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CerealId");

                    b.HasIndex("CircuitoId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("FilaId");

                    b.HasIndex("SectorId");

                    b.ToTable("OrdenesTransito");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.Patente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PatenteAcoplado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PatenteCamion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PatenteOpcional")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SujetoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SujetoId");

                    b.ToTable("Patentes");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.Rol", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.Sector", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Sectores");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.SectorHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdenTransitoId")
                        .HasColumnType("int");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrdenTransitoId");

                    b.HasIndex("SectorId");

                    b.ToTable("HistorialesSector");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.Sujeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ExternoId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<long>("NumeroDocumento")
                        .HasColumnType("bigint");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Sujetos");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.TipoSujeto", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("TiposSujeto");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.TransicionEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CircuitoId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoOrigenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CircuitoId");

                    b.HasIndex("EstadoDestinoId");

                    b.HasIndex("EstadoOrigenId");

                    b.ToTable("TransicionesEstado");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.UsuarioRol", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("UsuarioId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("UsuariosRoles");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.Zona", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Zonas");
                });

            modelBuilder.Entity("SujetoTipoSujeto", b =>
                {
                    b.Property<int>("SujetosId")
                        .HasColumnType("int");

                    b.Property<int>("TiposSujetoId")
                        .HasColumnType("int");

                    b.HasKey("SujetosId", "TiposSujetoId");

                    b.HasIndex("TiposSujetoId");

                    b.ToTable("SujetoTiposSujeto", (string)null);
                });

            modelBuilder.Entity("CerealFila", b =>
                {
                    b.HasOne("Soltec.axControl.Server.Model.Cereal", null)
                        .WithMany()
                        .HasForeignKey("CerealesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Soltec.axControl.Server.Model.Fila", null)
                        .WithMany()
                        .HasForeignKey("FilasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.Chofer", b =>
                {
                    b.HasOne("Soltec.axControl.Server.Model.Sujeto", "Sujeto")
                        .WithMany()
                        .HasForeignKey("SujetoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Soltec.axControl.Server.Model.Sujeto", "Transportista")
                        .WithMany("Choferes")
                        .HasForeignKey("TransportistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sujeto");

                    b.Navigation("Transportista");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.ComprobanteHistorial", b =>
                {
                    b.HasOne("Soltec.axControl.Server.Model.OrdenTransito", "OrdenTransito")
                        .WithMany("HistorialComprobantes")
                        .HasForeignKey("OrdenTransitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenTransito");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.EstadoHistorial", b =>
                {
                    b.HasOne("Soltec.axControl.Server.Model.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Soltec.axControl.Server.Model.OrdenTransito", "OrdenTransito")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("OrdenTransitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("OrdenTransito");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.Fila", b =>
                {
                    b.HasOne("Soltec.axControl.Server.Model.Zona", "Zona")
                        .WithMany("Filas")
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.FilaHistorial", b =>
                {
                    b.HasOne("Soltec.axControl.Server.Model.Fila", "Fila")
                        .WithMany()
                        .HasForeignKey("FilaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Soltec.axControl.Server.Model.OrdenTransito", "OrdenTransito")
                        .WithMany("HistorialFilas")
                        .HasForeignKey("OrdenTransitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fila");

                    b.Navigation("OrdenTransito");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.OrdenTransito", b =>
                {
                    b.HasOne("Soltec.axControl.Server.Model.Cereal", "Cereal")
                        .WithMany()
                        .HasForeignKey("CerealId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Soltec.axControl.Server.Model.Circuito", "Circuito")
                        .WithMany()
                        .HasForeignKey("CircuitoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Soltec.axControl.Server.Model.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Soltec.axControl.Server.Model.Fila", "Fila")
                        .WithMany()
                        .HasForeignKey("FilaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Soltec.axControl.Server.Model.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cereal");

                    b.Navigation("Circuito");

                    b.Navigation("Estado");

                    b.Navigation("Fila");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.Patente", b =>
                {
                    b.HasOne("Soltec.axControl.Server.Model.Sujeto", "Sujeto")
                        .WithMany("Patentes")
                        .HasForeignKey("SujetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sujeto");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.Rol", b =>
                {
                    b.HasOne("Soltec.axControl.Server.Model.Usuario", null)
                        .WithMany("Roles")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.SectorHistorial", b =>
                {
                    b.HasOne("Soltec.axControl.Server.Model.OrdenTransito", "OrdenTransito")
                        .WithMany("HistorialSectores")
                        .HasForeignKey("OrdenTransitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Soltec.axControl.Server.Model.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdenTransito");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.TransicionEstado", b =>
                {
                    b.HasOne("Soltec.axControl.Server.Model.Circuito", "Circuito")
                        .WithMany("Transiciones")
                        .HasForeignKey("CircuitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Soltec.axControl.Server.Model.Estado", "EstadoDestino")
                        .WithMany()
                        .HasForeignKey("EstadoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Soltec.axControl.Server.Model.Estado", "EstadoOrigen")
                        .WithMany()
                        .HasForeignKey("EstadoOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Circuito");

                    b.Navigation("EstadoDestino");

                    b.Navigation("EstadoOrigen");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.UsuarioRol", b =>
                {
                    b.HasOne("Soltec.axControl.Server.Model.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Soltec.axControl.Server.Model.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SujetoTipoSujeto", b =>
                {
                    b.HasOne("Soltec.axControl.Server.Model.Sujeto", null)
                        .WithMany()
                        .HasForeignKey("SujetosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Soltec.axControl.Server.Model.TipoSujeto", null)
                        .WithMany()
                        .HasForeignKey("TiposSujetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.Circuito", b =>
                {
                    b.Navigation("Transiciones");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.OrdenTransito", b =>
                {
                    b.Navigation("HistorialComprobantes");

                    b.Navigation("HistorialEstados");

                    b.Navigation("HistorialFilas");

                    b.Navigation("HistorialSectores");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.Sujeto", b =>
                {
                    b.Navigation("Choferes");

                    b.Navigation("Patentes");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.Usuario", b =>
                {
                    b.Navigation("Roles");

                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("Soltec.axControl.Server.Model.Zona", b =>
                {
                    b.Navigation("Filas");
                });
#pragma warning restore 612, 618
        }
    }
}
